name: Sync Strava with Notion

on:
  schedule:
    - cron: "0 * * * *" # Ejecuta la acción cada hora
  workflow_dispatch: # Permite ejecutar manualmente desde la interfaz de GitHub

jobs:
  sync:
    runs-on: ubuntu-latest # Usa un contenedor de Ubuntu para ejecutar el código

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Usa la versión más reciente de checkout

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Usa la versión más reciente de setup-node
        with:
          node-version: "16" # Usa Node.js 16

      - name: Install dependencies
        run: |
          npm install  # Instala las dependencias de tu proyecto

      - name: Run Strava to Notion Sync Script
        env:
          STRAVA_ACCESS_TOKEN: ${{ secrets.STRAVA_ACCESS_TOKEN }} # Token de acceso de Strava
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }} # Token de refresh de Strava
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }} # ID de cliente de Strava
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }} # Secreto de cliente de Strava
          NOTION_INTEGRATION_TOKEN: ${{ secrets.NOTION_INTEGRATION_TOKEN }} # Token de Notion
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }} # ID de la base de datos de Notion
        run: |
          node sync-strava.js  # Ejecuta el script
