name: Sync Strava with Notion

on:
  schedule:
    - cron: "0 */6 * * *" # Ejecuta la acción cada hora
  workflow_dispatch: # Permite ejecutar manualmente desde la interfaz de GitHub

jobs:
  sync:
    runs-on: ubuntu-latest # Usa un contenedor de Ubuntu para ejecutar el código

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Actualiza a la versión más reciente de checkout (v3)

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Actualiza a la versión más reciente de setup-node (v3)
        with:
          node-version: "16" # Usa Node.js 16

      - name: Install dependencies
        run: |
          npm install  # Instala las dependencias de tu proyecto

      - name: Run Strava to Notion Sync Script
        env:
          STRAVA_ACCESS_TOKEN: ${{ secrets.STRAVA_ACCESS_TOKEN }} # Accede al secreto de Strava
          NOTION_INTEGRATION_TOKEN: ${{ secrets.NOTION_INTEGRATION_TOKEN }} # Accede al secreto de Notion
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }} # Accede al ID de la base de datos
        run: |
          node sync-strava.js  # Ejecuta el script que sincroniza Strava con Notion
