name: Sync Strava Activities

on:
  schedule:
    # Ejecutar todos los días a las 2:00 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  run-sync:
    runs-on: ubuntu-latest

    steps:
      # Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Usa la versión de Node.js que prefieras

      # Instala las dependencias del proyecto
      - name: Install dependencies
        run: npm install

      # Ejecuta el script de sincronización
      - name: Run sync script
        run: node sync-strava.js
        env:
          STRAVA_ACCESS_TOKEN: ${{ secrets.STRAVA_ACCESS_TOKEN }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          NOTION_INTEGRATION_TOKEN: ${{ secrets.NOTION_INTEGRATION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
