name: Sync Strava with Notion

on:
  schedule:
    - cron: "0 * * * *" # Ejecuta la acción cada hora
  workflow_dispatch: # Permite ejecutar manualmente desde la interfaz de GitHub

jobs:
  test-env:
    runs-on: ubuntu-latest
    steps:
      - name: Print test secret
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          echo "Test secret: ${TEST_SECRET}"
